# proto/BUILD.bazel
load("@rules_cc//cc:defs.bzl", "cc_library", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "errors_proto",
    srcs = ["errors.proto"],
    strip_import_prefix = "/proto",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "trace_event_proto",
    srcs = ["trace_event.proto"],
    deps = [":errors_proto"],
    strip_import_prefix = "/proto",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "test_messages_proto",
    srcs = ["test_messages.proto"],
    strip_import_prefix = "/proto",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "mcp_spec_proto",
    srcs = ["mcp_spec.proto"],
    strip_import_prefix = "/proto",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "checkpoint_proto",
    srcs = ["checkpoint.proto"],
    strip_import_prefix = "/proto",
    visibility = ["//visibility:public"],
)

proto_library(
    name = "workflow_spec_proto",
    srcs = ["workflow_spec.proto"],
    strip_import_prefix = "/proto",
    deps = [":mcp_spec_proto"],
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "errors_cc_proto",
    deps = [":errors_proto"],
)

cc_proto_library(
    name = "trace_event_cc_proto",
    deps = [":trace_event_proto"],
)

cc_proto_library(
    name = "test_messages_cc_proto",
    deps = [":test_messages_proto"],
)

cc_proto_library(
    name = "mcp_spec_cc_proto",
    deps = [":mcp_spec_proto"],
)

cc_proto_library(
    name = "checkpoint_cc_proto",
    deps = [":checkpoint_proto"],
)

cc_proto_library(
    name = "workflow_spec_cc_proto",
    deps = [":workflow_spec_proto"],
)

cc_library(
    name = "agentflow_proto",
    deps = [
        ":checkpoint_cc_proto",
        ":errors_cc_proto",
        ":mcp_spec_cc_proto",
        ":test_messages_cc_proto",
        ":trace_event_cc_proto",
        ":workflow_spec_cc_proto",
    ],
    visibility = ["//visibility:public"],
)
